### ISSUE TITLE
Nested tests not logged

### ISSUE THREAD

**Issue by pe4enko** [fabriciorby/maven-surefire-junit5-tree-reporter#36] opened 2023-02-15 16:08 UTC
I have Test with 2 @Nested class in same level. 
After run test only one nested test class logged in result.

**Comment by pe4enko** [comment] 2023-02-15 16:15
Test
![image](https://user-images.githubusercontent.com/822445/219085765-9b9ee805-1606-4512-be68-c45c516c35b3.png)
Output
![image](https://user-images.githubusercontent.com/822445/219086210-25480c6b-c1f4-41fc-9e4e-81d090bf30a9.png)

**Comment by fabriciorby** [comment] 2023-04-13 11:24
Hey man! Thanks for reporting, I will mark as duplicate of #26 

I will take some time to rewrite this in a better way soon.

**Closed by fabriciorby** 2023-04-13 11:24 UTC
Labels: duplicate
